services:
  oneway_clipboard:
    image: ghcr.io/perevalov84/oneway_clipboard:main
    volumes:
      - ./data:/data
    environment:
      DB_PATH: "/data/data.json"
      KEY_PATH: "/data/.ssh"
    ports:
      - 5000:5000
    restart: unless-stopped
