[build-system]
requires = ['flit_core==3.12.0']
build-backend = "flit_core.buildapi"

[project]
name = "oneway_clipboard"
dynamic = ['version','description']
dependencies =[
    "flask",
    "paramiko >= 4.0.0",
    "dotenv >= 0.9.9"
]

[project.optional-dependencies]
test=[
    "pytest",
]